spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: catalog
          uri: ${CATALOG_ROUTE_URI:http://catalog.railway.internal}
          predicates:
            - Path=/api/v1/movies/**, /api/v1/categories/**, /api/v1/catalog/**

        - id: users
          uri: ${USERS_ROUTE_URI:http://users.railway.internal}
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**

        - id: transactions
          uri: ${TRANSACTIONS_ROUTE_URI:http://transactions.railway.internal}
          predicates:
            - Path=/api/v1/rentals/**

        - id: notifications
          uri: ${NOTIFICATIONS_ROUTE_URI:http://notifications.railway.internal}
          predicates:
            - Path=/api/v1/notifications/**

eureka:
  client:
    enabled: false

