spring.application.name=users
spring.config.import=optional:file:.env[.properties]

server.port=8082

spring.datasource.url=jdbc:postgresql://ep-purple-field-ambv85u7-pooler.c-5.us-east-1.aws.neon.tech/users_db?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

jwt.secret=${JWT_SECRET:change-this-secret-in-env-with-32-bytes}
jwt.expiration=${JWT_EXPIRATION:86400000}
