spring:
  application:
    name: notifications
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb+srv://admin_blockbuster:${MONGO_PASSWORD}@clusterfs1.sqmkchr.mongodb.net/notifications_db?appName=ClusterFS1

server:
  port: ${PORT:${SERVER_PORT:8084}}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

internal:
  api:
    key: ${INTERNAL_API_KEY:change-this-internal-api-key}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://${EUREKA_SERVER_HOSTPORT:localhost:8761}/eureka}
