# Configuracion del Servidor
spring.application.name=notifications
spring.config.import=optional:file:.env[.properties]
server.port=8084

# Configuracion de Base de Datos (MongoDB Atlas)
spring.mongodb.uri=mongodb+srv://admin_blockbuster:${MONGO_PASSWORD}@clusterfs1.sqmkchr.mongodb.net/notifications_db?appName=ClusterFS1

# Mostrar queries en consola para debug
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

internal.api.key=${INTERNAL_API_KEY:change-this-internal-api-key}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka