#1- Servidor
spring.application.name=transactions
server.port = 8083
#2- Configuración BD
spring.datasource.url=jdbc:postgresql://ep-purple-field-ambv85u7-pooler.c-5.us-east-1.aws.neon.tech/transactions_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#3- Configuración JPA
# Evitamos que Hibernate cree o modifique tablas automáticamente. Dejaremos que Flyway haga ese trabajo.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#4-  Flyway
spring.flyway.enabled=true