#1- Servidor
spring.application.name=transactions
spring.config.import=optional:file:.env[.properties]
server.port = 8083

#2- Configuracion BD
spring.datasource.url=jdbc:postgresql://ep-purple-field-ambv85u7-pooler.c-5.us-east-1.aws.neon.tech/transactions_db?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

#3- Configuracion JPA
# Evitamos que Hibernate cree o modifique tablas automaticamente. Dejaremos que Flyway haga ese trabajo.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#4- Flyway
spring.flyway.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

users.service.url=${USERS_SERVICE_URL:http://localhost:8082}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8081}
notifications.service.url=${NOTIFICATIONS_SERVICE_URL:http://localhost:8084}
internal.api.key=${INTERNAL_API_KEY:change-this-internal-api-key}
jwt.secret=${JWT_SECRET:Esta_es_una_clave_secreta_super_larga_y_segura_para_el_proyecto_blockbuster_2026}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.cloud.openfeign.client.config.usersClient.connectTimeout=5000
spring.cloud.openfeign.client.config.usersClient.readTimeout=5000
spring.cloud.openfeign.client.config.catalogClient.connectTimeout=5000
spring.cloud.openfeign.client.config.catalogClient.readTimeout=5000
spring.cloud.openfeign.client.config.notificationsClient.connectTimeout=5000
spring.cloud.openfeign.client.config.notificationsClient.readTimeout=5000
spring.cloud.openfeign.httpclient.hc5.enabled=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka