spring.application.name=catalog
server.port=8081
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://ep-purple-field-ambv85u7-pooler.c-5.us-east-1.aws.neon.tech/catalog_db?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO
